# Generated by Django 4.0.4 on 2022-05-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRequest',
        ),
    ]
